### PR TITLE
Improve Login page

### PR DESCRIPTION
**Pull request by fsmosca**
New login page.

image

### CODE REVIEW

**Comment by hunkim** [comment]
@fsmosca it looks good. Is there any reason that you closed this PR?

**Comment by fsmosca** [comment]
If deployed in the cloud like streamlit cloud, google auth will not work. I cannot solve it at the moment.

**Comment by hunkim** [comment]
I guess streamlit cloud blocks it. Can you find a workaround?

**Comment by mukundagujjar** [comment]
When deployed on Cloud, the "x-frame-options" header is set to deny. I [searched](https://www.googlecloudcommunity.com/gc/AppSheet-Q-A/X-Frame-Options-set-to-DENY-with-authentication-enabled/m-p/355022) a bit and found out that it is set that way for security reasons (to prevent clickjacking).
image

On my local machine, the header allows from account.google.com.
image

I guess this is the only primary issue that needs to be navigated around.

**Pull request merged**
